name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: |
        sudo mkdir -p /ros2_ws/src/net_bytes
        sudo chown -R $(whoami) /ros2_ws
        cd /ros2_ws/src/net_bytes
        rsync -av ./ /root/ros2_ws/src/net_bytes
        rosdep update
        rosdep install -i --from-path src --rosdistro humble -y
        bash -xv ./src/net_bytes/test/test.bash /root
