name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up workspace
      run: |
        # Create necessary directories and fix permissions
        sudo mkdir -p /ros2_ws/src/net_bytes
        sudo chown -R $(whoami) /ros2_ws

    - name: Sync files with rsync
      run: |
        # Sync files from the current directory to the target ROS workspace
        rsync -av ./ /ros2_ws/src/net_bytes/

    - name: Install dependencies
      run: |
        # Update rosdep and install dependencies
        rosdep update
        rosdep install -i --from-paths /ros2_ws/src --rosdistro humble -y

    - name: Source ROS 2 environment
      run: |
        # Ensure that ROS 2 is sourced so that ROS 2 commands are available
        source /opt/ros/humble/setup.bash

    - name: Build and run tests
      run: |
        # Build the workspace and run tests
        cd /ros2_ws
        colcon build
        source /ros2_ws/install/setup.bash
        bash -xv /ros2_ws/src/net_bytes/test/test.bash
